add_files ./fir/fir_0/fir_0.xci
add_files ./fir/fir_10/fir_10.xci
add_files ./fir/fir_11/fir_11.xci
add_files ./fir/fir_12/fir_12.xci
add_files ./fir/fir_13/fir_13.xci
add_files ./fir/fir_14/fir_14.xci
add_files ./fir/fir_15/fir_15.xci
add_files ./fir/fir_1/fir_1.xci
add_files ./fir/fir_2/fir_2.xci
add_files ./fir/fir_3/fir_3.xci
add_files ./fir/fir_4/fir_4.xci
add_files ./fir/fir_5/fir_5.xci
add_files ./fir/fir_6/fir_6.xci
add_files ./fir/fir_7/fir_7.xci
add_files ./fir/fir_8/fir_8.xci
add_files ./fir/fir_9/fir_9.xci
